import type { CopySlot } from "./types";

/** Wording that appears on every slide rather than belonging to one page. */
export const GLOBAL_COPY: CopySlot[] = [
  { key: "backButton", label: "Back button", default: "Back" },
  { key: "nextButton", label: "Next button", default: "Next" },
  { key: "pageCounter", label: "Page counter", default: "{current} / {total}", hint: "{current} and {total} are replaced with numbers." },
  { key: "flowProgressLabel", label: "Progress tracker: screen-reader title", default: "Your progress" },
  { key: "flowStageSigned", label: "Progress tracker: stage 1", default: "Agreement signed" },
  { key: "flowStageSignedShort", label: "Progress tracker: stage 1 (phone)", default: "Signed", hint: "Kept short so all three stages fit beside Back and Next on a phone." },
  { key: "flowStagePayment", label: "Progress tracker: stage 2", default: "Payment details" },
  { key: "flowStagePaymentShort", label: "Progress tracker: stage 2 (phone)", default: "Paid", hint: "Kept short so all three stages fit beside Back and Next on a phone." },
  { key: "flowStageOnboarding", label: "Progress tracker: stage 3", default: "Onboarding form" },
  { key: "flowStageOnboardingShort", label: "Progress tracker: stage 3 (phone)", default: "Setup", hint: "Kept short so all three stages fit beside Back and Next on a phone." },
  { key: "flowStageDone", label: "Progress tracker: screen-reader word for a finished stage", default: "done" },
  { key: "servicesSelectedOne", label: "Price bar: one service", default: "service selected" },
  { key: "servicesSelectedMany", label: "Price bar: several services", default: "services selected" },
  { key: "perMonthGst", label: "Price bar: per month", default: "+ GST per month" },
  { key: "discountEndsIn", label: "Countdown label", default: "Your discount ends in" },
  { key: "discountEndsInShort", label: "Countdown label (short)", default: "Discount ends in" },
  { key: "cartOpenLabel", label: "Price bar: open the basket", default: "View selections" },
  { key: "cartHideLabel", label: "Price bar: hide the basket", default: "Hide selections" },
  { key: "cartTitle", label: "Basket: title", default: "Your selections" },
  { key: "cartCountOne", label: "Basket: one service", default: "1 service" },
  { key: "cartCountMany", label: "Basket: several services", default: "{count} services", hint: "{count} is replaced with the number selected." },
  { key: "cartCloseButton", label: "Basket: close button", default: "Hide" },
  { key: "cartTermLabel", label: "Basket: contract length label", default: "Contract length" },
  { key: "cartPerMonth", label: "Basket: per month suffix", default: "/month" },
  { key: "cartOneOff", label: "Basket: one-off suffix", default: "one-off" },
  { key: "cartComplimentary", label: "Basket: complimentary price", default: "Complimentary" },
  { key: "cartSaveAmount", label: "Basket: saving on a line", default: "Save {amount}", hint: "{amount} is replaced with the saving." },
  { key: "cartEditButton", label: "Basket: go to the service's page", default: "Edit" },
  { key: "cartRemoveButton", label: "Basket: remove a service", default: "Remove" },
  { key: "cartFullPrice", label: "Basket: full price row", default: "Full price" },
  { key: "cartYouSave", label: "Basket: saving row", default: "You save" },
  { key: "cartMonthlyTotal", label: "Basket: monthly total", default: "Monthly total" },
  { key: "cartOneOffTotalSingle", label: "Basket: one-off total (one)", default: "One-off payment" },
  { key: "cartOneOffTotalPlural", label: "Basket: one-off total (several)", default: "One-off payments" },
  { key: "cartGstSuffixMonthly", label: "Basket: GST label on the monthly total", default: "+ GST /month" },
  { key: "cartGstSuffix", label: "Basket: GST label on a single payment", default: "+ GST" },
  { key: "cartProceedButton", label: "Basket: main button", default: "Review & sign" },
  { key: "cartPaymentButton", label: "Basket: main button once signed", default: "Add payment details" },
  { key: "cartEmptyTitle", label: "Basket: nothing selected, title", default: "Nothing in here yet" },
  { key: "cartEmptyBody", label: "Basket: nothing selected, message", default: "Add a service from any page and it will show up here, with your total.", multiline: true },
  { key: "linkNotFoundTitle", label: "Broken link: title", default: "Link Not Found" },
  { key: "linkNotFoundBody", label: "Broken link: message", default: "This link is invalid or has expired. Please contact your account manager for an updated link.", multiline: true },
  { key: "linkReplacedTitle", label: "Replaced link: title", default: "Link Replaced" },
  { key: "linkReplacedBody", label: "Replaced link: message", default: "A newer version has been sent to you. Please check your email for the latest link, or contact your account manager.", multiline: true },
];
