import type { CopySlot } from "./types";

export const INTAKE_COPY: CopySlot[] = [
  { key: "stepProgress", label: "Step counter", default: "Step {current} of {total}", hint: "{current} and {total} are replaced with numbers." },
  { key: "backButton", label: "Back button", default: "Back" },
  { key: "continueButton", label: "Continue button", default: "Continue" },
  { key: "submitButton", label: "Submit button", default: "Submit" },
  { key: "doneTitle", label: "Finished: title", default: "All Done!" },
  { key: "doneBody", label: "Finished: message", default: "Thank you for completing the onboarding form. Your dedicated marketer will be in touch to schedule your onboarding call.", multiline: true },
  { key: "downloadsTitle", label: "Finished: downloads heading", default: "Yours to keep" },
  { key: "downloadAction", label: "Finished: download link", default: "Download PDF", hint: "Shown on each document the client saves." },
  { key: "openAction", label: "Finished: open link", default: "Read online", hint: "Replaces the download wording when the full terms are a page you host rather than a file." },
  { key: "downloadAgreement", label: "Finished: agreement card", default: "The Agreement" },
  { key: "downloadAgreementNote", label: "Finished: agreement card, message", default: "The service agreement you signed, signature and all.", multiline: true },
  { key: "downloadTerms", label: "Finished: terms card", default: "Terms & Conditions" },
  { key: "downloadTermsNote", label: "Finished: terms card, message", default: "The terms your agreement was signed under.", multiline: true },
  { key: "downloadIntake", label: "Finished: onboarding form card", default: "Onboarding Form" },
  { key: "downloadIntakeNote", label: "Finished: onboarding form card, message", default: "Every answer you just gave us, written out in full.", multiline: true },
  { key: "lockedNote", label: "Finished: answers are locked", default: "Your answers are in and locked. If anything needs changing, tell your marketer and they'll sort it with you.", multiline: true },
  { key: "reviewResponses", label: "Review answers link", default: "Read back your answers" },
  { key: "reviewBanner", label: "Reviewing: read-only notice", default: "Submitted — these answers are read only." },
  { key: "reviewDone", label: "Reviewing: finish button", default: "Done" },
  { key: "addressStateOption", label: "Address: state dropdown", default: "State" },
  { key: "fileDropPrompt", label: "File upload: prompt", default: "Drop files here or click to browse" },
  { key: "fileUploading", label: "File upload: uploading", default: "Uploading..." },
  { key: "multiselectEmpty", label: "Multi-select: nothing chosen", default: "Select options..." },
  { key: "multiselectCount", label: "Multi-select: count", default: "{count} selected", hint: "{count} is replaced with a number." },
  { key: "providersNoneTitle", label: "Provider picker: none available", default: "No providers available for your area yet." },
  { key: "providersNoneBody", label: "Provider picker: none available, message", default: "Nothing to do here — continue to the next step and your account manager will arrange this with you directly.", multiline: true },
  { key: "providerPortfolioLink", label: "Provider picker: portfolio link", default: "Portfolio" },
  { key: "groupEntryLabel", label: "Repeating group: entry heading", default: "Entry {number}", hint: "{number} is replaced with the entry's position." },
  { key: "groupAddButton", label: "Repeating group: add button", default: "Add another" },
  { key: "sameAsLabel", label: "\"Same as\" checkbox", default: "Same as above", hint: "Used when the question's own same-as setting doesn't name a label." },
  { key: "linkNotFoundTitle", label: "Broken link: title", default: "Link Not Found" },
  { key: "linkNotFoundBody", label: "Broken link: message", default: "This onboarding link is invalid or has expired. Please contact your account manager for an updated link.", multiline: true },
  { key: "servicesErrorTitle", label: "Loading problem: title", default: "Error Loading Services" },
  { key: "servicesErrorBody", label: "Loading problem: message", default: "There was an error loading your services. Please contact your account manager for assistance.", multiline: true },
];
