import type { CopySlot } from "./types";

export const SUMMARY_COPY: CopySlot[] = [
  { key: "heading", label: "Heading", default: "Your Summary" },
  { key: "intro", label: "Intro", default: "Here's everything you've selected. Tap a service to see details.", multiline: true },
  { key: "emptyTitle", label: "Nothing selected: title", default: "No services selected yet." },
  { key: "emptyBody", label: "Nothing selected: message", default: "Browse the pages to add the services you want.", multiline: true },
  { key: "complimentary", label: "Complimentary label", default: "Complimentary" },
  { key: "perMonthShort", label: "Per month (short)", default: "/mo" },
  { key: "oneOffShort", label: "One-off (short)", default: "one-off" },
  { key: "weeklyBreakdown", label: "Weekly price breakdown", default: "{weekly}/week ({monthly}/month)", hint: "{weekly} and {monthly} are replaced with prices." },
  { key: "includedHeading", label: "Inclusions heading", default: "What's Included" },
  { key: "commitmentsHeading", label: "Commitments heading", default: "Your Commitments" },
  { key: "removeButton", label: "Remove button", default: "Remove this" },
  { key: "editButton", label: "Change selection button", default: "Change this", hint: "Takes the client back to the service's own slide. Hidden when this proposal has no slide for that service." },
  { key: "cardTitle", label: "Price card title", default: "Investment Summary" },
  { key: "free", label: "Free label", default: "Free" },
  { key: "forMonths", label: "Length of a monthly plan", default: "for {months} months", hint: "{months} is replaced with the number of months." },
  { key: "forOneMonth", label: "Length of a one-month plan", default: "for 1 month" },
  { key: "oneOffPayment", label: "One-off line label", default: "one-off payment" },
  { key: "fullPrice", label: "Full price label", default: "Full price" },
  { key: "youSave", label: "Saving label", default: "You save" },
  { key: "monthlyTotal", label: "Monthly total label", default: "Monthly Total" },
  { key: "gstSuffixMonthly", label: "Monthly total suffix", default: "/mo + GST" },
  { key: "gstSuffix", label: "One-off total suffix", default: "+ GST" },
  { key: "oneOffTotalSingle", label: "One-off total (one item)", default: "One-off payment" },
  { key: "oneOffTotalPlural", label: "One-off total (several items)", default: "One-off payments" },
  { key: "paymentCapturedTitle", label: "Payment on file: title", default: "Payment details captured" },
  { key: "paymentCapturedBody", label: "Payment on file: message", default: "Your payment information is on file. No further action needed.", multiline: true },
  { key: "addPaymentButton", label: "Add payment button", default: "Add your payment details" },
  { key: "proceedButton", label: "Proceed button", default: "Proceed to Signature" },
];
