// Writes .env.local (gitignored) at the repo root.

import { writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Returns the canonical env-var map for the new site.
 * Single source of truth for both .env.local and the Vercel env push.
 */
export function buildEnv({ supabaseUrl, anonKey, serviceRoleKey, dbPassword, baseUrl }) {
  return {
    NEXT_PUBLIC_SUPABASE_URL: supabaseUrl,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: anonKey,
    SUPABASE_SERVICE_ROLE_KEY: serviceRoleKey,
    SUPABASE_DB_PASSWORD: dbPassword,
    NEXT_PUBLIC_BASE_URL: baseUrl,
  };
}

export function writeEnvLocal(repoRoot, env) {
  const lines = [
    "# Generated by scripts/bootstrap.mjs — do not commit (gitignored).",
    `NEXT_PUBLIC_SUPABASE_URL=${env.NEXT_PUBLIC_SUPABASE_URL}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${env.NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
    "# Server-only. Used by admin server actions. NEVER expose to the client.",
    `SUPABASE_SERVICE_ROLE_KEY=${env.SUPABASE_SERVICE_ROLE_KEY}`,
    "# For future migrations / direct DB access.",
    `SUPABASE_DB_PASSWORD=${env.SUPABASE_DB_PASSWORD}`,
    `NEXT_PUBLIC_BASE_URL=${env.NEXT_PUBLIC_BASE_URL}`,
    "",
  ];
  writeFileSync(join(repoRoot, ".env.local"), lines.join("\n"));
}

/** Vars to push to Vercel. Excludes nothing — Vercel encrypts them at rest. */
export function envForVercel(env) {
  return Object.entries(env).map(([key, value]) => ({ key, value }));
}
